### ISSUE TITLE
WooCommerce doesn't work

### ISSUE THREAD

**Issue by solstudioim** [solstudioim/Chat-domain-button#1]
***This ticket was escalated from Zendesk by Ejayhan F:***

  **Ticket:** [#4](https://woothemes1654022967.zendesk.com/agent/tickets/4)
  **Type:** Ticket
  **Priority:** Normal
  **Requester:** Topbizkid
  **Organization:** -
  **Assignee:** Ejayhan F
***

Test only it's conflicting gz#4

gz#5

**Comment by solstudioim** [comment]
Agent comment from Ejayhan F in <a href='https://woothemes1654022967.zendesk.com/agent/tickets/4'>Zendesk ticket #4</a>:  Shared a workaround but didn't work for the user.
<br><p><em><small>°°°</small></em></p>

**Comment by solstudioim** [comment]
A PR is going to be introduced soon

**Comment by solstudioim** [comment]
This comment not to send to ZD

**Comment by solstudioim** [comment]
This not correct

**Comment by solstudioim** [comment]
Agent comment from Sol J in <a href='https://woothemes1654022967.zendesk.com/agent/tickets/4'>Zendesk ticket #4</a>:  The user came to chat again
<br><p><em><small>°°°</small></em></p>

**Comment by solstudioim** [comment]
Agent comment from Ejayhan F in <a href='https://woothemes1654022967.zendesk.com/agent/tickets/4'>Zendesk ticket #4</a>:  The workaround didn't work for the second time
<br><p><em><small>°°°</small></em></p>

**Comment by solstudioim** [comment]
Agent comment from Ejayhan F in <a href='https://woothemes1654022967.zendesk.com/agent/tickets/5'>Zendesk ticket #5</a>:  This was ejay
<br><p><em><small>°°°</small></em></p>

**Comment by sjejayhan** [comment]
That's correct

**Comment by sjejayhan** [comment]
This was closed
